version: '3'
services:
    netevent:
        image: lan2play/netevent
        ports:
            - '${APPPort:-5000}:5000'
        env_file: .env
        environment:
            DBProvider: "${DBProvider}"
            DBName: "${DBName}"
            DBServer: "${DBServer}"
            DBPort: "${DBPort}"
            DBUser: "${DBUser}"
            DBPassword: "${DBPassword}"
            TZ: '${TZ}'
        volumes:
            - netevent_data:/data
        networks:
            - netevent
        depends_on:
            - netevent_psql
        healthcheck:
          test: ["CMD-SHELL", "curl --fail http://localhost:5000/healthz || exit"]
          retries: 3
          timeout: 5s
            
    netevent_psql:
        image: 'postgres:latest'
        env_file: .env
        environment:
            POSTGRES_PASSWORD: '${DBPassword}'
            POSTGRES_USER: '${DBUser}'
            POSTGRES_DB: '${DBName}'
            TZ: '${TZ}'
        volumes:
            - netevent_psql:/var/lib/postgresql/data
        networks:
            - netevent
        healthcheck:
          test: ["CMD-SHELL", "pg_isready -U ${DBUser} -d ${DBName}"]
          retries: 3
          timeout: 5s

networks:
    netevent:
        driver: bridge

volumes:
  netevent_data:
        driver: local
  netevent_psql:
        driver: local