#!/usr/bin/env bash

if [[ "$DBProvider" = "psql" ]]
then 
    export DBConnection="Host=$DBServer;Port=$DBPort;Username=$DBUser;Password=$DBPassword;Database=$DBName"
    # Database Wait check
    echo "---------------"
    echo "WAITING FOR $DBServer:$DBPort..."
    wait-for.sh $DBServer:$DBPort --timeout=30 -- /NetEvent/NetEvent.Server
fi
if [[ "$DBProvider" = "sqlite" ]]
then 
    export DBConnection="Data Source=$DBName"
    /NetEvent/NetEvent.Server
fi