name: NetEvent_website_build

on:
  push:
    branches: [ OpenIdDict ]
    tags: [ v**]
    paths:
    - 'Docs/**'
    - 'packaging/Docs/**'
    - '.github/workflows/NetEvent_website_build.yml'
  pull_request:
    branches: [ OpenIdDict ]
    tags: [ v**]
    paths:
    - 'Docs/**'
    - 'packaging/Docs/**'
    - '.github/workflows/NetEvent_website_build.yml'

jobs:

  build_only:
    runs-on: ubuntu-latest
    if: ${{ (!startsWith(github.ref, 'refs/tags/v')) && (!contains(github.event.head_commit.message, 'forcepublish')) && github.event_name == 'pull_request'}}
    steps:
    - uses: actions/checkout@v3
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: ./Docs/docfx.json


  publish_prd:
    runs-on: ubuntu-latest
    if: ${{ (startsWith(github.ref, 'refs/tags/v') && github.event_name == 'push' && !(contains(github.ref, '-beta'))) || (contains(github.event.head_commit.message, 'forcepublish') && github.event_name == 'push') }}
    steps:
    - uses: actions/checkout@v3
    - uses: nikeee/docfx-action@v1.0.0
      name: Build Documentation
      with:
        args: ./Docs/docfx.json
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.NETEVENT_LAN2PLAY_DE_SSH }}
        name: id_rsa
        # config: ${{ secrets.SSH_CONFIG }} 
        known_hosts: unnecessary
        if_key_exists: fail 
    - name: git config
      run: git config --global user.email "ci@netevent.lan2play.de" && git config --global user.name "NetEvent CI"
    - name: clone pages repo
      run: git clone git@github.com:Lan2Play/netevent.lan2play.de.git
    - name: remove old things and add new
      run: rm -rf ./netevent.lan2play.de/docs/* && cp -rf ./Docs/_site/* ./netevent.lan2play.de/docs/
    - name: readd cname
      run: echo "netevent.lan2play.de" >> ./netevent.lan2play.de/docs/CNAME
    - name: push pages repo
      run: cd ./netevent.lan2play.de && if [ $(git status --short | wc -l) -gt 0 ]; then git add . && git commit -m "CI Build" && git push; fi
    


